// angular-extension/webview-ui/src/app/person/person.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, HostListener } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { vscode } from '../utilities/vscode';
import { VscodeTextfieldInputDirective } from '../vscode-textfield-input.directive';
import '@vscode-elements/elements/dist/vscode-label';
import '@vscode-elements/elements/dist/vscode-textfield';

@Component({
  selector: 'person-root',
  imports: [ReactiveFormsModule, VscodeTextfieldInputDirective],
  templateUrl: './person.component.html',
  styleUrl: '../app.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PersonComponent {
  firstname = new FormControl('');
  lastname = new FormControl('');
  personObject: any;

  constructor() {
    // Webviews are normally torn down when not visible and re-created when they become visible again.
    // State lets us save information across these re-loads
    const state = vscode.getState() as any;
    if (state) {
      this.updateContent(state.text);
    }
  }

  // Handle messages sent from the extension to the webview
  @HostListener('window:message', ['$event'])
  handleMessage(event: MessageEvent) {
    const message = event.data; // The json data that the extension sent
    switch (message.type) {
      case 'update':
        const text = message.text;

        // Update our webview's content
        this.updateContent(text);

        // Then persist state information.
        // This state is returned in the call to `vscode.getState` below when a webview is reloaded.
        vscode.setState({ text });
        return;
    }
  }

  /**
   * Update the data shown in the document in the webview.
   */
  updateContent(text: string) {
    if (text !== '') {
      this.personObject = JSON.parse(text);
      this.firstname.setValue(this.personObject.firstname);
      this.lastname.setValue(this.personObject.lastname);
    }
  }

  /**
   * Update the document in the extension.
   */
  updateDocument() {
    let firstname = this.firstname.value;
    let lastname = this.lastname.value;

    // wait 500 ms before updating the document
    // only update if in the meantime no other input was given
    setTimeout(() => {
      if (
        this.firstname.value === firstname &&
        this.lastname.value === lastname
      ) {
        this.personObject = {
          firstname: this.firstname.value,
          lastname: this.lastname.value,
        };

        vscode.postMessage({
          type: 'updateDocument',
          text: JSON.stringify(this.personObject, null, 2),
        });
      }
    }, 500);
  }
}

<main class="main">
  <h1>Angular Person Editor</h1>
  <div class="content">
    <div class="person">
      <div class="row">
        <vscode-label for="firstname">Firstname:</vscode-label>
        <div class="value">
          <vscode-textfield
            type="text"
            [formControl]="firstname"
            (input)="updateDocument()"
          />
        </div>
      </div>
      <div class="row">
        <vscode-label for="lastname">Lastname:</vscode-label>
        <div class="value">
          <vscode-textfield
            type="text"
            [formControl]="lastname"
            (input)="updateDocument()"
          />
        </div>
      </div>
    </div>
  </div>
</main>

// react-extension/webview-ui/src/Person.tsx
import { useState } from "react";
import { vscode } from "./utilities/vscode";
import "./App.css";
import "@vscode-elements/elements/dist/vscode-label";
import "@vscode-elements/elements/dist/vscode-textfield";

function Person() {
  const [personObject, setPersonObject] = useState(loadState);

  /**
   * Load the initial state via vscode API or return an empty object as initial state.
   */
  function loadState() {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const state = vscode.getState() as any;
    if (state) {
      return JSON.parse(state.text);
    }

    return {
      firstname: "",
      lastname: "",
    };
  }

  // Handle messages sent from the extension to the webview
  window.addEventListener("message", (event) => {
    const message = event.data; // The json data that the extension sent
    switch (message.type) {
      case "update": {
        const text = message.text;

        // Update our webview's content
        updateContent(text);

        // Then persist state information.
        // This state is returned in the call to `vscode.getState` below when a webview is reloaded.
        vscode.setState({ text });

        return;
      }
    }
  });

  /**
   * Update the data shown in the document in the webview.
   */
  function updateContent(text: string) {
    if (text !== "") {
      const parsed = JSON.parse(text);
      setPersonObject({
        firstname: parsed.firstname,
        lastname: parsed.lastname,
      });
    }
  }

  /**
   * Update the document in the extension.
   */
  function updateDocument() {
    vscode.postMessage({
      type: "updateDocument",
      text: JSON.stringify(personObject, null, 2),
    });
  }

  return (
    <>
      <main className="main">
        <h1>React Person Editor</h1>
        <div className="content">
          <div className="person">
            <div className="row">
              <vscode-label htmlFor="firstname" className="vscode-label">
                Firstname:
              </vscode-label>
              <div className="value">
                <vscode-textfield
                  type="text"
                  id="firstname"
                  className="vscode-textfield"
                  value={personObject.firstname}
                  onInput={(event) => {
                    const value = event.currentTarget.value;
                    const target = event.currentTarget;
                    // wait 500 ms before updating the document
                    // only update if in the meantime no other input was given
                    setTimeout(() => {
                      if (value === target.value) {
                        personObject.firstname = value;
                        updateDocument();
                      }
                    }, 500);
                  }}
                />
              </div>
            </div>
            <div className="row">
              <vscode-label htmlFor="lastname" className="vscode-label">
                Lastname:
              </vscode-label>
              <div className="value">
                <vscode-textfield
                  type="text"
                  id="lastname"
                  className="vscode-textfield"
                  value={personObject.lastname}
                  onInput={(event) => {
                    const value = event.currentTarget.value;
                    const target = event.currentTarget;
                    // wait 500 ms before updating the document
                    // only update if in the meantime no other input was given
                    setTimeout(() => {
                      if (value === target.value) {
                        personObject.lastname = value;
                        updateDocument();
                      }
                    }, 500);
                  }}
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default Person;
